cd ../cs108-project
rm -rf ../submission_clean#variable
LATEX = pdflatex

.PHONY: all clean

all: report.pdf
# Compile the PDF
report.pdf: report.tex
	$(LATEX) report.tex
	$(LATEX) report.tex

# Remove auxiliary files generated by Latex while compiling into pdf
clean:
	rm -f *.aux *.log *.out *.toc *.pdf
